name: FirmXtract-DumprX
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: https://dl.samfwpremium.cloud/115c940791722c987cac76f655b3f926ZwP5-ZEI9oZJLPogyqJAZrj6sfgIchd_VBMxYHqTqLR8EYGgIMxnWQP-Xz_M3Cc6jjD5xXgA28JjY3_JNtzGlULXNnGqvO9B0bnbQ8mHD8pRMUuK2nfbojuMB7_IOARY8OMxp1WlNd8fponavpkUVNfgng5wTYeh7z3B86uJiMIzE0UXx5VeQ4sJH9UEVnph6NOVfkcMJ0fJO2tEg8-hSxyLr_I2GDiLRnxOTtGP_6xQNMX8gnvbDDwV6RzsCjbDot_S_mj6-r-V9C__PloNDUbFfSrUfmpqJBrjX0FeuDXgmtuy2jKwBUM-mrtGKlxdA_BXKvpc3KLTlukvTTMKtZU8EvHf1Cc33bqHSb4PMAVPllS6RQfSygpd2F3N30acfpWrWN7URp9VqCHHIpXCBdjkWEd1wz8iK4wRlotyn_8XoeK_NW40ejDRQfx0nsnLFPY4X7qnkVM8wFXBDScbifLlGQMuvqp6eh3rd2k3ygV5GqyP9l0euypBYhAwa3dtTaIrkCwb73UY5U6-duHWn3IWQTlSWIufEzrbI2cMtZtZy4ATnxGQhSJ1fFFUwQg4V6EhH9t4R5MsaLLkwYWkdu-IuHP2NmCqAZcrYWQ-GcqJ8Mo45TwP_zxZ-OhxXjE3PillXcn62gBwkmxi4t-BBPpjLQPgq7z_CP-rw6xi8Y6LLrjtSNAzY7XXmXvgfl3qRT5DgrkS2hRiXLn1iXI317Kydp2pVPwtzpJM1hYU01d4k8gJKZE-BIcv2amu6OAj6HmsU1o9QgkDo6hB2RFWgKoO7Foh3RdGaQ-9dJmd2nfq74hr5kdEXNVdExMOhwzHiQPtUdHydYfTIF0seKRHJWQVF0j0T3FH4wePnDCHLC-aSRQsd3xm88zmdGM8RkqPQBsTceMqgN1OWaRswiDU01DWLFf8TGbI4zUGCnrkjcZyxEO7eJ2OVQ5il1aO4jhVGhEBkxYC0T8b_UuT_0VMCUtesS1sg6n8khA2qYtBcp9PLem4G6DmBWV-E9it1mUF6_h3pHQNYNOiBWJz0Y25n2IGywz598cO5Bi_1Nrx5arnJC5yVZ1q7abAiu8nXEZ2YNrkjX71krOdbjyOTtlNVQ?file_name=SAMFW.COM_SM-A057F_XXV_A057FXXU7CXK6_fac.zip
        required: true
       # Requester
      USER_NAME:
        description: "justin
        required: false
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  # Requester
  USERNAME: ${{ github.event.inputs.USERNAME }}
  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Set Workflow URL
         run: |
               WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
               echo "WORKFLOW_URL=$WORKFLOW_URL" >> $GITHUB_ENV
       - name: Give the user the run link
         run: |
               curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.GROUP_CHAT_ID }} -d text="Follow progress here: $WORKFLOW_URL"
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main       
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/DumprX/DumprX.git DumprX

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |

              sudo bash setup.sh
              sudo apt install -y f2fs-tools
              sudo apt install neofetch -y
              mkdir -p ~/.ssh
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
              git config --global user.name "Galax1eo"
              git config --global user.email "galaxieodelight@gmail.com"

       - name: Setup Config envs
         working-directory: DumprX
         run: |
              # echo "${{ secrets.GIT_TOKEN }}" > .github_token
              # echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token  # Only for Gitlab
              echo "${{ secrets.GITLAB_GROUP }}" > .gitlab_group  # Only for Gitlab
              echo "${{ secrets.GITLAB_INSTANCE }}" > .gitlab_instance  # Only for Gitlab
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_rsa  # Only for Gitlab
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat
              chmod 600 ~/.ssh/id_rsa
              if grep -q "HOST \*" ~/.ssh/config && grep -q "StrictHostKeyChecking no" ~/.ssh/config; then

              echo "Changes are already present"

              else

              echo "HOST *" > ~/.ssh/config

              echo "StrictHostKeyChecking no" >> ~/.ssh/config

              fi

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: DumprX
         run: |
              ./dumper.sh "$ROM_URL"
       - name: Telegram Notification
         if: ${{ cancelled() || failure() }}
         continue-on-error: true
         uses: xinthink/action-telegram@v1.1
         with:
          chatId: ${{ secrets.GROUP_CHAT_ID }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          jobStatus: ${{ job.status }}
          skipSuccess: true
